<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="60.0000" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2020-05-04T21:12:56" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Find game by name" timestamp="2020-05-04T21:12:56" tests="1" file="/home/berkendorff/Learning/ТРПЗ/QA_KA-75/SeleniumPageObject/tests/findGame.test.js" time="60.0000" failures="1">
    <testcase name="Find game by name should find game by name" time="60.0000" classname="should find game by name">
      <failure message="Timeout of 60000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (/home/berkendorff/Learning/ТРПЗ/QA_KA-75/SeleniumPageObject/tests/findGame.test.js)" type="Error"><![CDATA[Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/berkendorff/Learning/ТРПЗ/QA_KA-75/SeleniumPageObject/tests/findGame.test.js)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)]]></failure>
    </testcase>
  </testsuite>
</testsuites>